# Generated by Django 3.0.6 on 2020-05-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Catalog", "verbose_name_plural": "Catalogs"},
        ),
    ]
